<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @category    ViraXpress
 * @package     ViraXpress_Widget
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php $mediaUrl = $block->getBaseMediaUrl();
$baseUrl = $block->getBaseUrl(); ?>
<div data-content-type="row" data-appearance="full-bleed" data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-background-type="image" data-video-loop="true" data-video-play-only-visible="true" data-video-lazy-load="true" data-video-fallback-src="" data-element="main" data-pb-style="MTWJ3AF">
    <h2 class="text-2xl font-semibold text-black mb-6 container mt-16 leading-normal" data-content-type="heading" data-appearance="default" data-element="main" data-pb-style="L8L9L5L">Top Categories</h2>
    <div class="pagebuilder-column-group container top-categories" data-background-images="{}" data-content-type="column-group" data-appearance="default" data-grid-size="12" data-element="main" data-pb-style="OW71L8K">
        <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main" data-pb-style="A4NVNEA">
            <div class="pagebuilder-column relative overflow-hidden" data-content-type="column" data-appearance="full-height" data-background-images="{}" data-element="main" data-pb-style="D1VHKOB">
                <figure class="rounded-xl overflow-hidden" data-content-type="image" data-appearance="full-width" data-element="main" data-pb-style="WDOX0BO">
                    <img class="pagebuilder-mobile-hidden" src="<?= $escaper->escapeUrl($mediaUrl.'wysiwyg/cat_women_VX.webp') ?>" alt="" title="" data-element="desktop_image" data-pb-style="W06IG35">
                    <img class="pagebuilder-mobile-only" src="<?= $escaper->escapeUrl($mediaUrl.'wysiwyg/cat_women_VX.webp') ?>" alt="" title="" data-element="mobile_image" data-pb-style="HXIE6N2">
                </figure>
                <div data-content-type="buttons" data-appearance="inline" data-same-width="false" data-element="main" data-pb-style="PW1OKCK">
                    <div class="text-lg font-medium flex justify-center items-center absolute -bottom-full left-0 opacity-0 w-full h-full transition-all duration-300 ease-in-out" data-content-type="button-item" data-appearance="default" data-element="main" data-pb-style="L0KTH7P">
                        <a class="pagebuilder-button-link" href="<?= $escaper->escapeUrl($baseUrl.'women/tops-women.html') ?>" target="" data-link-type="category" data-element="link" data-pb-style="SR5N6YE">
                            <span data-element="link_text">Womens</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="pagebuilder-column relative overflow-hidden" data-content-type="column" data-appearance="full-height" data-background-images="{}" data-element="main" data-pb-style="M3GGRT9">
                <figure class="rounded-xl overflow-hidden" data-content-type="image" data-appearance="full-width" data-element="main" data-pb-style="RRPBLHR">
                    <img class="pagebuilder-mobile-hidden" src="<?= $escaper->escapeUrl($mediaUrl.'wysiwyg/cat_men_VX.webp') ?>" alt="" title="" data-element="desktop_image" data-pb-style="KHQNANB">
                    <img class="pagebuilder-mobile-only" src="<?= $escaper->escapeUrl($mediaUrl.'wysiwyg/cat_men_VX.webp') ?>" alt="" title="" data-element="mobile_image" data-pb-style="DI4L9JO">
                </figure>
                <div data-content-type="buttons" data-appearance="inline" data-same-width="false" data-element="main" data-pb-style="L9LKW1D">
                    <div class="text-lg font-medium flex justify-center items-center absolute -bottom-full left-0 opacity-0 w-full h-full transition-all duration-300 ease-in-out" data-content-type="button-item" data-appearance="default" data-element="main" data-pb-style="JSEU3DR">
                        <a class="pagebuilder-button-link" href="<?= $escaper->escapeUrl($baseUrl.'men/tops-men.html') ?>" target="" data-link-type="category" data-element="link" data-pb-style="CD00EKB">
                            <span data-element="link_text">Mens</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="pagebuilder-column relative overflow-hidden" data-content-type="column" data-appearance="full-height" data-background-images="{}" data-element="main" data-pb-style="FE0M0YG">
                <figure class="rounded-xl overflow-hidden" data-content-type="image" data-appearance="full-width" data-element="main" data-pb-style="B5T535D">
                    <img class="pagebuilder-mobile-hidden" src="<?= $escaper->escapeUrl($mediaUrl.'wysiwyg/cat-kid_1.webp') ?>" alt="" title="" data-element="desktop_image" data-pb-style="JL0KK2N">
                    <img class="pagebuilder-mobile-only" src="<?= $escaper->escapeUrl($mediaUrl.'wysiwyg/cat-kid_1.webp') ?>" alt="" title="" data-element="mobile_image" data-pb-style="PFJPU4R">
                </figure>
                <div data-content-type="buttons" data-appearance="inline" data-same-width="false" data-element="main" data-pb-style="XYGDYS9">
                    <div class="text-lg font-medium flex justify-center items-center absolute -bottom-full left-0 opacity-0 w-full h-full transition-all duration-300 ease-in-out" data-content-type="button-item" data-appearance="default" data-element="main" data-pb-style="VPUGKC1">
                        <a class="pagebuilder-button-link" href="<?= $escaper->escapeUrl($baseUrl.'gear/fitness-equipment.html') ?>" target="" data-link-type="category" data-element="link" data-pb-style="OA3RD69">
                            <span data-element="link_text">Kids</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
